name: 'End-to-End tests'
description: 'Performs Cypress tests'

runs:
  using: "composite"
  steps:
    - name: Setup 🔧
      uses: ./.github/actions/setup

    - name: Verify Cypress install 🔧
      shell: bash
      run: npm run cy:verify

    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        browser: electron
        build: npm run build:test
        install: false
        start: npm run preview:test
        wait-on: 'http://localhost:3000'
